# kubectl run -it --rm --image=mysql:5.6 --restart=Never mysql-client -- mysql -h mysqlservice -ppassword
apiVersion: v1
kind: Namespace
metadata:
  name: horsefly-development
---
apiVersion: v1
kind: Service
metadata:
  name: msvc1-db-service
  namespace: horsefly-development
  labels:
    app: msvc1-db
spec:
  ports:
  - port: 3306
    targetPort: 3306
    protocol: TCP
  selector:
    app: msvc1-db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: msvc1-db-deployment
  namespace: horsefly-development
spec:
  selector:
    matchLabels:
      app: msvc1-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: msvc1-db
    spec:
      containers:
      - image: mysql:5.6
        name: msvc1-db-container
        env:
          # Use secret in real usage
        - name: MYSQL_ROOT_PASSWORD
          value: password
        ports:
        - containerPort: 3306
          name: msvc1-db-port
        volumeMounts:
        - name: msvc1-db-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: msvc1-db-persistent-storage
        persistentVolumeClaim:
          claimName: msvc1-db-claim-restore
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: msvc1-db-claim
  namespace: horsefly-development
spec:
  storageClassName: rook-ceph-block
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 8Gi
