apiVersion: snapshot.storage.k8s.io/v1alpha1
kind: VolumeSnapshot
metadata:
  name: msvc1-snapshot-1
  namespace: horsefly-development
spec:
  snapshotClassName: csi-rbdplugin-snapclass
  source:
    name: msvc1-db-claim
    kind: PersistentVolumeClaim
