apiVersion: v1
kind: Namespace
metadata:
  name: nginx-test-1
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  namespace: nginx-test-1
spec:
  containers:
    - name: nginx-container
      image: nginx:1.19
