# kubectl -n sonarqube run -it --rm --image=mysql:5.6 --restart=Never mysql-client -- mysql -h msvc1-db-service -ppassword 
# show databases
# create database sonar
---
apiVersion: v1
kind: Service
metadata:
  name: msvc1-db-service
  namespace: sonarqube
  labels:
    app: msvc1-db
spec:
  ports:
  - port: 3306
    targetPort: 3306
    protocol: TCP
  selector:
    app: msvc1-db
---
apiVersion: v1
kind: Secret
metadata:
  name: sonarqube-mysql-secret
data:
  password: cGFzc3dvcmQ=
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: msvc1-db-deployment
  namespace: sonarqube
spec:
  selector:
    matchLabels:
      app: msvc1-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: msvc1-db
    spec:
      containers:
      - image: mysql:5.6
        name: msvc1-db-container
        env:
          # Use secret in real usage
        - name: MYSQL_ROOT_PASSWORD
          # value: password
          valueFrom:
              secretKeyRef:
                name: sonarqube-mysql-secret
                key: password
        ports:
        - containerPort: 3306
          name: msvc1-db-ct-pt
        volumeMounts:
        - name: msvc1-db-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: msvc1-db-persistent-storage
        persistentVolumeClaim:
          claimName: msvc1-db-claim
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: msvc1-db-claim
  namespace: sonarqube
spec:
  storageClassName: rook-ceph-block
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 8Gi
