# kubectl -n sonarqube exec --stdin --tty mysql-client -- /bin/sh
# mysql -h msvc1-db-service -ppassword
# show databases;
# create database sonar;
apiVersion: v1
kind: Pod
metadata:
  name: mysql-client
spec:
  containers:
  - image: mysql:5.6
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: mysql-cnt
  nodeSelector:
    kubernetes.io/hostname: k8sworker000.management.skyfall.io
  restartPolicy: Never
