apiVersion: v1
kind: Pod
metadata:
  name: busybox
spec:
  volumes:
  - name: busy-vol
    persistentVolumeClaim:
      claimName: jnlp-claim
  containers:
  - image: busybox
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: busybox
    volumeMounts:
    - mountPath: "/mnt"
      name: busy-vol
  nodeSelector:
    kubernetes.io/hostname: k8sworker000.management.skyfall.io
  restartPolicy: Always
